version: '3.9'

services:
  web:
    container_name: web_container
    build:
      context: .
    entrypoint: bash
    command: >
      -c "cd /code/app && uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    volumes:
      - ./alembic:/code/alembic
      - ./app:/code/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres_network
    restart: unless-stopped

  db:
    container_name: db_container
    image: postgres:13.4-alpine3.14
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
